### ISSUE TITLE
Implement or derive Default for Span

### ISSUE THREAD

**Issue by ebkalderon** [brendanzab/codespan#117]
Prior to the release of `codespan` 0.4.0, the `codespan::Span` type used to derive `Default`. I personally found this quite handy when hacking on ASTs where I did not care about the span information, and I could conveniently specify  `Default::default()` everywhere a `Span` was expected without having to import it.

In particular, I also happen to find the `Default` implementation handy when writing macros that construct ASTs, since they eliminate the need to depend on `codespan` and import the type. So if a downstream crate were to import the macro, it would not require the user to depend on `codespan`, or for the crate author to re-export `codespan::Span` for the macro to use.

Are there any technical reasons to not derive `Default` on `Span`? If there aren't, it would be a nice touch in the ergonomics department.

**Comment by brendanzab** [comment]
Does `Span::intitial()` solve your problem? I've not really been a fan of `Default` because it doesn't really offer any suggestion of what the semantics of this default value should be in relation to anything else, so I tend to avoid it in favour of more descriptive method names with dedicated documentation.

**Comment by brendanzab** [comment]
Alternatively I _have_ been wondering if I should make codespan's numbers non-zero by default in order to allow people to use `Option`s for span information without wasting byte space. That way you could use `None` for things that have no real location information. Just an idea though.

**Comment by ebkalderon** [comment]
`Span::initial()` does precisely what I am looking for, yes, and I have been using it since the 0.4.0 update. However, consider an AST crate that depends on `codespan`, and there is some downstream user who wishes to manually construct an unspanned AST.

It would be quite convenient for users who don't care about the span information to simply specify `Default::default()` in areas expecting a `Span` and not have to pull in `codespan` as a dependency needlessly. Similarly, public macros for constructing unspanned ASTs now require the user to either depend on `codespan` themselves, or the AST crate can re-export `codespan` for the macro to consume but with `#[doc(hidden)]`.

**Comment by brendanzab** [comment]
Anyway, I've published the changes!

**Comment by ebkalderon** [comment]
Thanks for the quick response, @brendanzab! Much appreciated.
