### ISSUE TITLE
Incorrect number alignment in rendered diagnostics

### ISSUE THREAD

**Issue by ebkalderon** [brendanzab/codespan#130]
There appears to be an issue when rendering diagnostics' line numbers with `codespan` 0.5. The output looks something like this:

```
error: unterminated block comment

    ┌── stdin:8:5 ───
    │
 8 │ ╭     /*
 9 │ │     buildInputs = [
 10 │ │       (nixpkgs.rustChannelOf { channel = "stable"; }).rust
 11 │ │       # nixpkgs.darwin.apple_sdk.frameworks.Security
 12 │ │       # nixpkgs.darwin.apple_sdk.frameworks.CoreServices
 13 │ │       nixpkgs.jq
 14 │ │       nixpkgs.sqlite
 15 │ │     ];
 16 │ │   }
 17 │ │
    │ ╰^ unterminated block comment
    │
```

The line numbers are aligned to the left instead of the right, thereby breaking the ASCII art.

**Comment by ebkalderon** [comment]
Alternatively, if it is desired to keep the numbers aligned to the left, the printable width of the line number being displayed should be taken into account when rendering the gutter.

**Comment by ebkalderon** [comment]
I found [this line](https://github.com/brendanzab/codespan/blob/master/codespan-reporting/src/term/views/source_snippet/gutter.rs#L36) for rendering the gutter, and I was surprised to see from the format string that the line numbers are aligned to the right rather than the left. Attempting to switch the format string from `"{line: >width$}"` to `"{line: <width$}"` doesn't seem to fix the problem. Perhaps some trimming of trailing whitespace is occurring elsewhere down the line?

**Comment by ebkalderon** [comment]
For reference, I am using `StandardStream::stdout(ColorChoice::Auto)` and `codespan_reporting::term::Config::default()` to render the diagnostic snippet in the issue description.

**Comment by ebkalderon** [comment]
The invocation of `Gutter::new().emit()` which is responsible for rendering line 8 in the snippet above appears to be [here](https://github.com/brendanzab/codespan/blob/master/codespan-reporting/src/term/views/source_snippet/mod.rs#L215), and it's using the same `gutter_padding` value as everywhere else (which should be `2` because the bottom-most line number is two digits wide), but it's not working as expected. I can confirm that inserting a `write!(writer, " ")?;` immediately after this line fixes the alignment, but this can hardly be considered a general fix.

**Comment by brendanzab** [comment]
Hmm, yeah, I was trying to use the `"{line: >width$}"` to have the correct indentation! Weird that it's broken 🤔

**Comment by ebkalderon** [comment]
@brendanzab If you'd like to debug the live application with `codespan-reporting` that produced this output, you can clone https://github.com/ebkalderon/nix-language-server and run the `viewer` example in the `nix-parser` subcrate with some erroneous code (easiest is to have an unterminated C-style block comment) to trigger the diagnostic shown in the issue description. If you can have that comment span over multiple lines, passing over lines 9 and 10, you should be able to see the result.

**Comment by dtolnay** [comment]
I hit this too. Repro against current master branch:

```rust
use codespan::Files;
use codespan_reporting::diagnostic::{Diagnostic, Label};
use codespan_reporting::term::emit;
use codespan_reporting::term::termcolor::{ColorChoice, StandardStream};

fn main() {
    let mut files = Files::new();
    let content = "\n\n\n\n\n\naaaaaaaaaa\n\nbbbbbbbbbb\ncccccccccc\n";
    let file = files.add("path/to", content);
    let diagnostic = Diagnostic::new_error("it failed", Label::new(file, 8..34, "error"));
    let writer = StandardStream::stderr(ColorChoice::Auto);
    let config = codespan_reporting::term::Config::default();
    emit(&mut writer.lock(), &config, &files, &diagnostic).unwrap();
}
```

```console
error: it failed

    ┌── path/to:7:3 ───
    │
 7 │   aaaaaaaaaa
    │ ╭───^
 8 │ │ 
 9 │ │ bbbbbbbbbb
 10 │ │ cccccccccc
    │ ╰─────^ error
    │
```
