### ISSUE TITLE
Make the Label an optional part of the Diagnostic

### ISSUE THREAD

**Issue by prybicki** [brendanzab/codespan#138]
Sometimes there's no specific place in the source file to point - consider a program in C which does not have main() function.

**Comment by jyn514** [comment]
@prybicki the way I currently handle this is by pointing to the end of the file. YMMV, though.

**Comment by brendanzab** [comment]
Been experimenting with a new API that will let you do something like:

```rust
Diagnostic::error("oops")
```

This will emit something like:

```
error: oops
```
