### ISSUE TITLE
Publish 0.6.1

### ISSUE THREAD

**Issue by dtolnay** [brendanzab/codespan#142]
@brendanzab, when you get a chance it would be great to get a patch release for the bugfix in https://github.com/brendanzab/codespan/pull/139#issuecomment-569470761. Thanks!

cc @ebkalderon

**Comment by brendanzab** [comment]
It will probably need to be a 0.7 due to lsp-types making lots of breaking changes that could have knock-on effects to downstream consumers. Will that be ok? See gluon-lang/lsp-types#17.

**Comment by dtolnay** [comment]
Sure, that would work.

**Comment by ebkalderon** [comment]
Sounds good to me! Feel free to bump.

**Comment by dtolnay** [comment]
Alternatively if you have other changes planned for 0.7 that are not ready yet, please cherry-pick my fix back to before the lsp-types update and publish 0.6.1.

**Comment by brendanzab** [comment]
0.7.0 should now be published as of #148!

**Comment by dtolnay** [comment]
Cheers! I have a library I will be announcing this week that relies on codespan so I am glad this was released in time.

**Comment by brendanzab** [comment]
Oooh, looking forward to it!
