### ISSUE TITLE
Rename codespan-reporting

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#171]
With the addition of the `Files` trait, `codespan-reporting` is now decoupled entirely from `codespan`. I'm wondering if we should consider renaming it? `language-reporting` is [already taken](https://github.com/wycats/language-reporting), but maybe we could call it something else:

- `text-reporting`
- `code-reporting`
- `lang-reporting`
- `source-reporting`

Curious if anybody has any thoughts!

**Comment by jyn514** [comment]
I don't see why it has to be renamed? It's still developed along with codespan and I think keeping name recognition is important, if it were changed to language-reporting I would think it was a different project.

**Comment by brendanzab** [comment]
I guess it's more that `codespan` is moving to be more a crate for tracking source metrics that _happens_ to implement the `Files` trait in `codespan-reporting`, rather than being the core of this monorepo, as the name implies. But I dunno.

**Comment by brendanzab** [comment]
I'm cool if we stew on this somewhat, however.

**Comment by Johann150** [comment]
I agree with jyn514 here.
Also I think it would cause some not so nice effects when the crate name changes on crates.io. As it is not really necessary it would be better to forgo all this potential trouble.

Changing names is always some trouble, that's why naming is so hard.

**Comment by brendanzab** [comment]
Ok, let's close this then
