### ISSUE TITLE
Release v0.9.0

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#186]
I'm pretty happy with decoupling of `codespan_reporting` from `codespan`, the `codespan_reporting::Files` API as it stands, and the current incremental improvements to the multi-label output. I think we'll be able to do further improvements to the multi-label output without changing the `Files` trait too much. As such, I'm thinking I'll do a release of v0.9.0 tomorrow.

**Comment by brendanzab** [comment]
The thing that I'm most interested in getting feedback on is whether the [`codespan_reporting::Files` trait](https://github.com/brendanzab/codespan/blob/9944b31be2ebd663541f1f81bb4ea6f1aad24bc9/codespan-reporting/src/files.rs#L5-L38) looks reasonable as it stands. I've tried to make it as simple as possible while retaining a reasonable amount of flexibility, but I might have missed some things!

https://github.com/brendanzab/codespan/blob/9944b31be2ebd663541f1f81bb4ea6f1aad24bc9/codespan-reporting/src/files.rs#L5-L38

**Comment by jyn514** [comment]
Can you explain the difference between Origin and Source? It looks like Source is meant to be the source code since it has `AsRef<str>`, what is Origin?

**Comment by brendanzab** [comment]
Oh, I should probably add better docs for those. `Origin` is like the file name. I could just call it `Name`, perhaps?

**Comment by jyn514** [comment]
What's wrong with `File`?

**Comment by jyn514** [comment]
Also, I assume this is the display filename, not just an arbitrary `Vec<u8>`? I store the absolute filepaths of files so that I know which directory to look in for local includes (`#include "main.h"`).

**Comment by brendanzab** [comment]
Yeah, this is the display name. Eg. it might be relative to the current directory.
