### ISSUE TITLE
Return error values rather than panicking when rendering diagnostics.

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#189]
We have lots of `unwraps` and fallible slice accesses in the diagnostic rendering at the moment that could result in user-facing panics when calling `codespan_reporting::term::emit`. Most of these panicking calls are currently localised to [`codespan_reporting::term::views`](https://github.com/brendanzab/codespan/blob/master/codespan-reporting/src/term/views.rs).
The panics could result from invalid file IDs, or invalid line ranges, say if an incremental compiler updated the underlying file before an error has been printed.

What should we do in this case? Should we panic? Return a richer error enum than a `std::io::Error`? Render something to the console?

Related: #140

**Comment by jyn514** [comment]
I think it's fine to panic as long as the panics are documented (including things like a slice that's not on a UTF8 code point boundary, c.f. https://github.com/jyn514/rcc/issues/265).

**Comment by brendanzab** [comment]
The feedback I've got in private is:

> …crashing limits the usability of your crate. If someone wants to use it in a place where the application is high availability and/or interactive, it's going to cause issues. I also noticed that catching panics as they unwind isn't 100%. Seems like async/await, at least initially, caused panics to not be catch-able.

So we might want to think about ways to provide a non-panicking API.

**Comment by ratmice** [comment]
FWIW, I ran into one of these in [prop](https://github.com/ratmice/prop) stemming from `codespan_reporting::term::emit`, if it helps, you can find the test case here: [tests.rs](https://github.com/ratmice/prop/blob/master/src/tests.rs#L74) `cargo test bad_unicode -- --nocapture`

```
error: Invalid token

   ┌── foo:1:1 ───
   │
 1 │ ₐₑₒₓₔₕₖₗₘₙₚₛₜ₀₁₂₃₄₅₆₇₈₉ ≔ ⊤
thread 'tests::bad_unicode' panicked at 'byte index 1 is not a char boundary; it is inside 'ₐ' (bytes 0..3) of `ₐₑₒₓₔₕₖₗₘₙₚₛₜ₀₁₂₃₄₅₆₇₈₉ ≔ ⊤`', src/libcore/str/mod.rs:2069:5
```

With the relevant part of the backtrace being:

```
  18: codespan_reporting::term::renderer::Renderer::mark_single
             at .../github.com-1ecc6299db9ec823/codespan-reporting-0.9.1/src/term/renderer.rs:438
  19: codespan_reporting::term::renderer::Renderer::render_source_line
             at .../github.com-1ecc6299db9ec823/codespan-reporting-0.9.1/src/term/renderer.rs:277
  20: codespan_reporting::term::views::RichDiagnostic<FileId>::render
             at .../github.com-1ecc6299db9ec823/codespan-reporting-0.9.1/src/term/views.rs:230
  21: codespan_reporting::term::emit
             at .../github.com-1ecc6299db9ec823/codespan-reporting-0.9.1/src/term.rs:96
  22: prop::test_util::expect_fail
```

**Comment by jyn514** [comment]
@ratmice I think you need to pass a byte index, not a char index. Passing an index to the start of the second char (`3`) would have the behavior you requested.

**Comment by ratmice** [comment]
@jyn514 thanks that helps, I pushed a fairly terrible [fix](https://github.com/ratmice/prop/pull/12) afaict though I have to start iterating the whole source from the beginning :dagger: to extend the range to a .char_indices boundary that overlaps it.

I'll have to see if I can get the lexer to pass return .char_indices() rather than the current Range(0, 1) when it fails.

**Comment by brendanzab** [comment]
Wondering if this would be better off as a separate issue? But yeah, that is a frustratingly bad workaround - I would have expected LALRPOP's built-in lexer to always return positions at a valid byte boundary.

Do note that Rust has [`str::is_char_boundary`](https://doc.rust-lang.org/std/primitive.str.html#method.is_char_boundary), which would reduce the amount of iteration you need to do.

**Comment by brendanzab** [comment]
One thing we could do though is to always slice along valid character boundaries internally in the renderer.
