### ISSUE TITLE
Builder DSL for diagnostics and labels looks clunky after autoformatting

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#20]
Our builder DSL for diagnostic messages doesn't really look the nicest when passed through rustfmt. An example:

https://github.com/brendanzab/pikelet/blob/4f2327f0dfa9ebdb6b48ff3f01574db6f3421775/src/semantics/errors.rs

Maybe we could switch around how we pass arguments and call methods so that it reads a little nicer?

**Comment by Marwes** [comment]
> Maybe we could switch around how we pass arguments and call methods so that it reads a little nicer?

Got an example? Not able to visualize it.

I guess we could remove the `new_` and `with_` prefixes on the functions?
