### ISSUE TITLE
Optional file names

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#200]
It would be nice if the file name was optional. This might make use cases such as REPLs easier to support. I'm not sure what to put in the snippet locus though. Does this look ok?

```
   ┌── 7:13 ───
   │
 7 │ {-# BUILTIN NATRAL Nat #-}
   │             ^^^^^^ unknown builtin
   │
   = there is a builtin with a similar name: `NATURAL`
```

**Comment by jyn514** [comment]
If I were building a REPL, the whole concept of line numbers no longer really makes sense, but I think the filename is easy to work around, just make it `<stdin>` or such.

**Comment by brendanzab** [comment]
Some REPLs allow for multiple lines 🙃

**Comment by brendanzab** [comment]
`<stdin>` is a good idea though!

Perhaps we could see if anyone chimes in on this issue in the future with particular use cases before implementing this.

**Comment by Marwes** [comment]
Yeah, `<stdin>` or `<repl>` would be what I'd use as well.

**Comment by brendanzab** [comment]
Ok, used that in https://github.com/brendanzab/codespan/pull/204/commits/a9d2ee172ff149f98a741e6d1e8b4485c4150659 🙂

**Comment by ratmice** [comment]
I am of the opinion that it shouldn't be optional, but required, and that the caller needs to be making up one like the above change is doing, and if the caller is not in a position to make one up, the file descriptor it needs to extract the filename from in-band data.

I tend to define them in-band so you can shoot code through network pipes, and not have to deal with -all- files being named after a file descriptor.

**Comment by brendanzab** [comment]
Ok, gonna close this, as folks seem to be agreed that a file name is useful! Feel free to speak up if you disagree however!
