### ISSUE TITLE
Highlight text pointed to by labels

### ISSUE THREAD

**Issue by dtolnay** [brendanzab/codespan#206]
I noticed that codespan-reporting 0.9 is no longer highlighting the file characters pointed to by labels. For my use case I think I found that the highlighted way was preferable. Is this something that you would be open to bringing back as an option?

<br>

### codespan-reporting 0.8.0:

![Screenshot from 2020-03-18 15-00-30](https://user-images.githubusercontent.com/1940490/77011536-517ddc80-6929-11ea-99b2-445031ed702f.png)

### codespan-reporting 0.9.0:

![Screenshot from 2020-03-18 14-58-02](https://user-images.githubusercontent.com/1940490/77011535-50e54600-6929-11ea-8033-2d44965b423c.png)

**Comment by jyn514** [comment]
Relevant PR: https://github.com/brendanzab/codespan/pull/168

**Comment by jyn514** [comment]
Maybe https://github.com/brendanzab/codespan/issues/100 and highlighting text could be made mutually exclusive? That would look a little odd visually anyway.

**Comment by brendanzab** [comment]
Yeah, I'm currently in the process of trying to implement #100, and the highlighted code sections were rather hard to deal with - ie. you need to figure out which to prioiritise (perhaps primary spans?).

As an aside I've also noticed that the diagnostics begin to look super over-bearing when multiline source code is highlighted in colour.

**Comment by brendanzab** [comment]
Had another look at this today. This is the relevant part of the code that we'd need to change:

https://github.com/brendanzab/codespan/blob/d4181931e6534b83b229767176a88d288b0cbb72/codespan-reporting/src/term/renderer.rs#L268-L270

Sketching it out, it might look something like this:

```rust
            // Write source text
            write!(self, " ")?;
            for (byte_index, ch) in source.char_indices() {
                // TODO: Check if in primary multi-line label
                // TODO: Check if in primary single-line label
                // TODO: Do tab-stop calculation here, rather than using `self.config.source(self.writer)`
                write!(self, "{}", ch)?;
            }
            // TODO: undo styling if necessary
            write!(self, "\n")?;
```

I'm thinking we'd only highlight primary labels.
