### ISSUE TITLE
Consider using right-angle corner characters for multiline labels

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#213]
I've [had reports](https://github.com/brendanzab/codespan/pull/210#issuecomment-603176285) that under some browser configurations + font installations, the [rounded corner box drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) are missing, and so they fall-back to something less than ideal:

![](https://user-images.githubusercontent.com/23638587/77480165-95745400-6df7-11ea-933d-f808bb736de4.png)

This is really frustrating as I really liked the softer, snakey look of the rounded corner characters. This appears enough that we might have to consider using the right angle corners instead. We could retain the ability to configure them however.

For example this:

```
error[E0308]: match arms have incompatible types

   ┌── codespan/src/file.rs:1:9 ───
   │
 1 │   ╭         match line_index.compare(self.last_line_index()) {
 2 │   │             Ordering::Less => Ok(self.line_starts()[line_index.to_usize()]),
   │   │                               --------------------------------------------- this is found to be of type `Result<ByteIndex, LineIndexOutOfBoundsError>`
 3 │   │             Ordering::Equal => Ok(self.source_span().end()),
   │   │                                ---------------------------- this is found to be of type `Result<ByteIndex, LineIndexOutOfBoundsError>`
 4 │   │             Ordering::Greater => LineIndexOutOfBoundsError {
   │ ╭─│──────────────────────────────────^
 5 │ │ │                 given: line_index,
 6 │ │ │                 max: self.last_line_index(),
 7 │ │ │             },
   │ ╰─│─────────────^ expected enum `Result`, found struct `LineIndexOutOfBoundsError`
 8 │   │         }
   │   ╰─────────' `match` arms have incompatible types
   │
   = expected type `Result<ByteIndex, LineIndexOutOfBoundsError>`
        found type `LineIndexOutOfBoundsError`
```
...would become:
```
error[E0308]: match arms have incompatible types

   ┌── codespan/src/file.rs:1:9 ───
   │
 1 │   ┌         match line_index.compare(self.last_line_index()) {
 2 │   │             Ordering::Less => Ok(self.line_starts()[line_index.to_usize()]),
   │   │                               --------------------------------------------- this is found to be of type `Result<ByteIndex, LineIndexOutOfBoundsError>`
 3 │   │             Ordering::Equal => Ok(self.source_span().end()),
   │   │                                ---------------------------- this is found to be of type `Result<ByteIndex, LineIndexOutOfBoundsError>`
 4 │   │             Ordering::Greater => LineIndexOutOfBoundsError {
   │ ┌─│──────────────────────────────────^
 5 │ │ │                 given: line_index,
 6 │ │ │                 max: self.last_line_index(),
 7 │ │ │             },
   │ └─│─────────────^ expected enum `Result`, found struct `LineIndexOutOfBoundsError`
 8 │   │         }
   │   └─────────' `match` arms have incompatible types
   │
   = expected type `Result<ByteIndex, LineIndexOutOfBoundsError>`
        found type `LineIndexOutOfBoundsError`
```

**Comment by brendanzab** [comment]
I'd be really interested if folks could comment if they are also seeing this issue! I know it does show up for me in pre-formatted text in Gitter and Discord, but for now I've been focused on making it look good in the terminal.

**Comment by jyn514** [comment]
Ok, it looks like this is a browser issue. If I look at this in a terminal it's fine, but in the browser
 the `^` underneath `LineIndexOutOfBoundsError` is way over to the right, even in the version without curly lines.

Terminal (no curly lines):
![2020-03-24-19:30:44](https://user-images.githubusercontent.com/23638587/77486371-f9057e00-6e05-11ea-8f4b-d778200b1a5e.png)

Browser (no curly lines):
![browser](https://user-images.githubusercontent.com/23638587/77486180-6c5ac000-6e05-11ea-8da9-6c6034d3c9ba.png)

Terminal (curly lines):
![2020-03-24-19:31:25](https://user-images.githubusercontent.com/23638587/77486406-120e2f00-6e06-11ea-8271-f3c329235eaf.png)

Browser (curly lines): same as issue but I linked it for completeness.
![browser curly](https://user-images.githubusercontent.com/23638587/77480165-95745400-6df7-11ea-933d-f808bb736de4.png)

**Comment by Johann150** [comment]
This can be decided by implementers by changing the values in [`codespan_reporting::term::Chars`](https://docs.rs/codespan-reporting/0.11.0/codespan_reporting/term/struct.Chars.html).
