### ISSUE TITLE
Better JSON support?

### ISSUE THREAD

**Issue by oOBoomberOo** [brendanzab/codespan#216]
Currently, I'm using [serde_json](https://lib.rs/crates/serde_json) crate to deserialize JSON data and validating its data and then report a diagnostic back to codespan-reporting. The problem is that `serde` does not store the position of each field so there is no way to report an error in "codespan" style.

**Comment by brendanzab** [comment]
Yeah! This seems like something that would be really nice to have! I'm not sure if serde supports positional information - we might have to do some digging on this, perhaps on the issue tracker?

**Comment by oOBoomberOo** [comment]
Yeah, I did try to implement something similar but look like the position information does not get handed out to us until at the very end when there is a deserialize error which isn't very helpful.
We might even need to create our own json implementation.

**Comment by brendanzab** [comment]
It might be good to see if you can chat to the serde people directly to see if they have any ideas on how to get this to work. 🤔

**Comment by oOBoomberOo** [comment]
In [serde ignored](https://github.com/dtolnay/serde-ignored) crate, it seems to gather the path data in deserializing progress and call a function when that path is ignored. Maybe we can do something similar and return an error when it's deserializing a field that we want and then we can use `serde_json::Error` struct to get the line and column number?

**Comment by brendanzab** [comment]
What would be helpful is getting the byte offset 🤔 - even better, the byte range.

**Comment by oOBoomberOo** [comment]
After one nightly feature and a bit of head-scratching, I manage to [implement it](https://github.com/oOBoomberOo/json_peek) (part of it at least) but even with this `serde` still doesn't give the correct column data to us. `serde` just really doesn't want to cooperate huh?

**Comment by oOBoomberOo** [comment]
[This updated version](https://github.com/oOBoomberOo/json_peek) actually works more than half of the time now!

**Comment by brendanzab** [comment]
oooh, very cool!

**Comment by brendanzab** [comment]
Ok, I'm going to close this issue for now, feel free to reopen if you have any other issues!
