### ISSUE TITLE
Panics when sending invalid byte indexes to codespan-reporting.

### ISSUE THREAD

**Issue by ratmice** [brendanzab/codespan#224]
In issue #189 I ran into an issue with a bug in a lexer, where it was giving byte indexes not on a char boundary, passing those on to codespan-reporting resulted in panics, It was proposed there to open a separate issue for that.

I have run into another instance of this, which (I haven't fully looked into yet).  With quite a different cause.  I uploaded a repostory here containing a [json-pop](https://github.com/ratmice/json-pop), 

In this new case, we're trying to actually display a unicode error that the input contains invalid utf8, so when trying to display the source of the error then causes the error display to fail.  

I don't have a very good testcase for it yet as the testsuite isn't running through codespan-reporting yet. You'll find the string [here](https://github.com/ratmice/json-pop/blob/41f8d4d7228401b083b7aace5ca7e1a8c132e223/src/lib.rs#L80), and it fails with the non-codespan println! error reporting the testsuite currently goes through.

**Comment by jyn514** [comment]
How can a `String` be invalid UTF8?

**Comment by ratmice** [comment]
it's an `&str`, but good question none the less.  Perhaps its getting through from an `from_utf8_unchecked` call in a dependency being the start of a valid sequence? :confused:

**Comment by jyn514** [comment]
I agree the panics aren't ideal, but what should codespan do instead? It's not possible to print only part of a character.

**Comment by ratmice** [comment]
It's a good question, while admittedly not yet being very familiar with codespan internals,
if it would be possible to get a slice via the `buffer[range.start..]` and then iterate over `char_indices()` until it finds a character index `>= range.end` and use that for displaying the character?
