### ISSUE TITLE
Bump lsp_types to 0.74.X

### ISSUE THREAD

**Issue by segeljakt** [brendanzab/codespan#239]
`lsp_types` version 0.74.0 introduces a new type https://github.com/gluon-lang/lsp-types/commit/046dabf78b9b45d275de44a5517ef592280abea2

`codespan` has `lsp_types` version `0.73.0`. Currently compilation seems to fail with:

```rust
error[E0308]: mismatched types
  --> src/linter.rs:30:29
   |
30 | / ...                   byte_index_to_position(&files, id, ByteIndex(range.start as u32))
31 | | ...                       .unwrap(),
   | |___________________________________^ expected struct `lsp_types::Position`, found a different struct `lsp_types::Position`
```

**Comment by brendanzab** [comment]
Sounds like `cargo update` fixed this! https://gitter.im/codespan-rs/Lobby?at=5eae9effd898fe7a3761f792
