### ISSUE TITLE
Render labels pointing to the same line in a cleaner way

### ISSUE THREAD

**Issue by RDambrosio016** [brendanzab/codespan#247]
Currently, codespan will render labels pointing to close places in the source code in a way which i personally believe does not look very good, this is a sample from one of my projects

```
error[ParseError]: Unterminated object literal

   ┌── tests\main.js:1:1 ───
   │
 1 │ {a b c d
   │ - Object literal starts here
   │         ^ File ends here
   │
```

I think that looks kind of ugly, i believe that the first label should be broken into a second line with a pipe, and the second label should be rendered normally, yielding: 

```
error[ParseError]: Unterminated object literal

   ┌── tests\main.js:1:1 ───
   │
 1 │ {a b c d
   │ ┬       ^ File ends here
   │ │ Object literal starts here   
   │
```

I feel this way is a lot cleaner, it does not overlap, and is clearer to understand.

**Comment by brendanzab** [comment]
Are you using the latest version? I recently updated it in #241, which was published in v0.9.4

**Comment by RDambrosio016** [comment]
I am not, i was using 0.9.2, it seems to be fixed in 0.9.4, thank you!

**Comment by brendanzab** [comment]
No worries! Yes, the old one was confusing! 😆

**Comment by RDambrosio016** [comment]
However, i wonder why for secondary labels it doesnt use `┬`, it would be properly joined and look better in my opinion
