### ISSUE TITLE
How to remove files from Files database?

### ISSUE THREAD

**Issue by Timmmm** [brendanzab/codespan#248]
In [`Files`](https://docs.rs/codespan/0.9.4/codespan/struct.Files.html) I can see `add()` and `update()` but there's no `remove()`?

**Comment by brendanzab** [comment]
The idea behind this was to keep the file ids stable, but to be honest if you're wanting to do stuff like this I'd highly recommend looking into making your own implementation of `codespan_reporting::Files`! I could never really get a solution for `codespan` that worked for all use cases, and I think it's probably better if these are designed on a per-use case basis.

**Comment by brendanzab** [comment]
I'm ok with accepting a PR for this for what it's worth - even if it goes against my original ideas for how `codespan::Files` would work (ie. deleting would involve clearing an existing file and crating a new one).

**Comment by Johann150** [comment]
I'll close this since there has not been any action on this, and it is not really how the API is intended to be used.
