### ISSUE TITLE
Add the ability to create labels which point to separate ranges inside of a line

### ISSUE THREAD

**Issue by RDambrosio016** [brendanzab/codespan#256]
Labels currently only point to a single range in a line, this is fine for most use cases, however, it would be handy to have labels which can point to separate ranges inside of lines. A practical use case for this is function arguments, oftentimes you need to point to multiple arguments but multiple labels ends up being kind of ugly. It would be great if there was a way to have a label which points to all of those arguments.

Something like 
```
1 | function a(foo, bar, baz) 
  |            ^^^       ^^^ These arguments are not allowed
```

or perhaps 

```
1 | function a(foo, bar, baz) 
  |            ^^^_______^^^ These arguments are not allowed
```
This would likely end up being a separate struct, perhaps `MultirangeLabel`, as implementing this into label would be a big breaking change.

**Comment by brendanzab** [comment]
Could you solve this with two labels, with the last label having a message?

**Comment by RDambrosio016** [comment]
Ah it seems that works! it does not seem to cause issues with labels in between them either, ill go ahead and close this 👍
