### ISSUE TITLE
File column/line should consistently point to the first primary label instead of the first label

### ISSUE THREAD

**Issue by RDambrosio016** [brendanzab/codespan#259]
Currently when you have a diagnostic, and that diagnostic contains 2 labels, say, one secondary at `1:1` and one primary at `6:3`, the column/line at the top of the diagnostic on rich rendering shows `1:1`, this should instead point to the first primary label, which seems to be the case for short rendering. When you use short rendering it points to `6:3`, this should be made consistent across rendering types.

**Comment by jyn514** [comment]
It would help if you could post a screenshot or text of what you're talking about.

**Comment by RDambrosio016** [comment]
> It would help if you could post a screenshot or example of what you're talking about.

Yeah sorry, i forgot to do that, here is an example 
![Label mismatch](https://imgur.com/r0ZJa1f.png)

**Comment by Johann150** [comment]
I created a possible solution, but it is not completely universal: The labels have to be added to the diagnostic in a specific order (e.g. primary labels before secondary labels). I don't know how others use it, but the way I use it and in the tests this is always done. Maybe this is a requirement that could be added?

**Comment by Johann150** [comment]
I noticed in the example in the other thread that this issue might not really be resolved yet. The current behaviour is to update the locus only to earlier locations and only if the style of the label is greater or equal to the last "earliest" one found. This means that in the given example the locus is shown at the big secondary label which surrounds the primary label.

What the behaviour should instead be is to update the locus if a label of higher style is found, **or** if a label with an earlier start and equal style is found. If done this way the locus would be at the primary label, which it should be.
