### ISSUE TITLE
Introduce macro to create diagnostics

### ISSUE THREAD

**Issue by Stupremee** [brendanzab/codespan#273]
It would be nice to have a macro that can create a `Diagnostic`.
Currently, the code to create a `Diagnostic` can be very clumsy and messy.
E.g.
```rust
let d = Diagnostic::error();
let label = Label::primary(file, span)
    .with_message(format!("expected '{}', found '{}'", expected, found));
d.with_message("unexpected token")
    .with_labels(vec![label])
    .with_code("E123")
    .with_notes(vec!["this token is wrong".to_string()])
```
A good macro could replace the code above with something like this:
```rust
diagnostic! {
    error => "unexpected token",
    label: primary(format!("expected '{}', found '{}'", expected, found), file, span),
    code: "E123",
    note: "this token is wrong",
}
```

**Comment by Johann150** [comment]
Why not

```Rust
let d = Diagnostic::error()
    .with_message("unexpected token")
    .with_code("E123")
    .with_labels(vec![
        Label::primary(file, span)
            .with_message(format!("expected '{}', found '{}'", expected, found))
    ])
    .with_notes(vec![
        "this token is wrong".to_string()
    ]);
```

**Comment by Stupremee** [comment]
That would work too, but imo it still doesn't look very nice.

**Comment by brendanzab** [comment]
To be honest I'm a tad wary of exposing macros like this unless a _really_ compelling case is made. So I'm on the fence here. If we choose to add this it will be another thing we'll need to maintain. 😅

**Comment by brendanzab** [comment]
I'm definitely interested in ways of improving the ergonomics of building diagnostics though - it's more I consider macros to be the last resort here, if that makes sense!

**Comment by Johann150** [comment]
As no other arguments have been put forth, it is not convincing that this is really necessary.
