### ISSUE TITLE
Add an easy way to get spans from filemaps

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#28]
At the moment you need to go through the `CodeMap` to get a new span. And example of this is here:

https://github.com/pikelet-lang/pikelet/blob/0d8eaa35a7169cf9d4466acd08cbe301b72e590e/src/syntax/parse/lexer.rs#L245-L252

This is not very discoverable, and a couple of users have [been caught up on this before](https://gitter.im/codespan-rs/Lobby?at=5b3ee65a81816669a434a012)!

Perhaps we could have a `FileMap::span_for` method. Or perhaps a `SpanCreator` thingy that is `Copy`. That way folks could pass it around without having to worry about ownership.

**Comment by Marwes** [comment]
> Or perhaps a SpanCreator thingy that is Copy. That way folks could pass it around without having to worry about ownership.

Arguably the span that `FileMap` returns is a `SpanCreator`, it is just not easy to discover :/.

**Comment by brendanzab** [comment]
Haha true! :D

**Comment by brendanzab** [comment]
This was more relevant to the old API
