### ISSUE TITLE
Position is off by 2 characters with some strings

### ISSUE THREAD

**Issue by fmonniot** [brendanzab/codespan#288]
Hello there,

First of all, thanks for making this library. It's great to be able to emit high quality messages with such ease.

While working on a side project of mine, I found that some characters combination seems to be confusing the library. Here is an example of such error, with the rust code to reproduce below. Hopefully it's enough to help find the root cause.

```txt
note: position is correct
  ┌─ Float.fun:1:1
  │
1 │ 1.602e−19 == (1.602 * 10^-19)
  │ ^^^^^ 1.602

bug: position is off by 2 characters
  ┌─ Float.fun:1:9
  │
1 │ 1.602e−19 == (1.602 * 10^-19)
  │         ^^              ^^ 19
  │         │                
  │         ==
```

Test for the above output:

```rust
#[cfg(test)]
mod test {

    use codespan_reporting::diagnostic::{Diagnostic, Label};
    use codespan_reporting::files::SimpleFile;
    use codespan_reporting::term::termcolor::{ColorChoice, StandardStream};
    use codespan_reporting::term;

    #[test]
    fn fail_on_negative_exponential() {

        let file = SimpleFile::new("Float.fun", "1.602e−19 == (1.602 * 10^-19)");

        // Error reporter
        let writer = StandardStream::stderr(ColorChoice::Always);
        let config = codespan_reporting::term::Config {
            tab_width: 2,
            ..codespan_reporting::term::Config::default()
        };

        // diagnostic
        let diag = Diagnostic::note()
            .with_message(format!("position is correct"))
            .with_labels(vec![
                Label::primary((), 0..5).with_message("1.602"),
            ]);

        let diag2 = Diagnostic::bug()
            .with_message(format!("position is off by 2 characters"))
            .with_labels(vec![
                Label::primary((), 10..12).with_message("=="),
                Label::primary((), 26..28).with_message("19"),
            ]);

        term::emit(&mut writer.lock(), &config, &file, &diag).unwrap();
        term::emit(&mut writer.lock(), &config, &file, &diag2).unwrap();
    }
}
```

**Comment by brendanzab** [comment]
Hmmm, very strange! Might be something messing with the character width calculation? Eg. using `unicode-width`? 🤔

**Comment by Johann150** [comment]
This is a user error: 
I discovered that the first minus is not U+002D `HYPHEN-MINUS`, what one would get from pressing <kbd>-</kbd>. Instead it is U+2212 `MINUS-SIGN`. Since codespan uses byte indices ([see documentation here](https://docs.rs/codespan-reporting/0.9.5/codespan_reporting/diagnostic/struct.Label.html#structfield.range)) and this character takes 2 bytes in UTF-8, the indices are off. I copied your test case and only replaced the character to its usual form and it worked fine.

```rust
let file = SimpleFile::new("Float.fun", "1.602e-19 == (1.602 * 10^-19)");
```

```text
note: position is correct
  ┌─ Float.fun:1:1
  │
1 │ 1.602e-19 == (1.602 * 10^-19)
  │ ^^^^^ 1.602

bug: position is off by 2 characters
  ┌─ Float.fun:1:11
  │
1 │ 1.602e-19 == (1.602 * 10^-19)
  │           ^^              ^^ 19
  │           │
  │           ==
```

**Comment by ratmice** [comment]
I've looked a little but it doesn't seem like it is actually unicode-width, for instance the following (unicode-width) code all works fine, and the lines at https://github.com/brendanzab/codespan/blob/master/codespan-reporting/src/term/renderer.rs#L683 hitting the `MINUS-SIGN` is `unwrap`'ing Some(1) for that character.

```
{
    let teststr = "1.602e−19 == (1.602 * 10^-19)";
    let teststr2 = "1.602e−19 ";
    let teststr3 = "−";
    assert!(UnicodeWidthStr::width(teststr) == 29);
    assert!(UnicodeWidthStr::width(teststr2) == 10);
    assert!(UnicodeWidthStr::width(teststr3) == 1);
    assert!(UnicodeWidthChar::width('−').unwrap() == 1);
}
```

**Comment by fmonniot** [comment]
Well, I wouldn't have though of checking for a different minus sign. Thanks @Johann150 and sorry for the boggus report.

**Comment by brendanzab** [comment]
No worries! Thanks, it could have been a bug! :)

**Comment by brendanzab** [comment]
Oh, and thanks for the nice bug report, it was really well written!
