### ISSUE TITLE
Allow for configuring the number of lines of source snippet around a label

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#29]
This would allow us to give users more context of problems.

Here is an example from Reason:

![](https://user-images.githubusercontent.com/1909539/29709301-ab04eac6-8940-11e7-8d2b-c65f808b6be8.png)

**Comment by lpil** [comment]
This feature would be very useful for me, thank you :)

**Comment by Johann150** [comment]
Is this related to #125 ?

**Comment by elkowar** [comment]
Would be great if this was implemented. Is there anything specific holding this back? If not, I'd be open to trying myself at a PR for this

**Comment by elkowar** [comment]
I wrote up a mock implementation in https://github.com/elkowar/codespan/commit/fa4d5f899a017a1884cbf1529ac8f85244c62183
This is most likely a pretty bad way to do this, although I'm not sure how i'd improve it - I'm really not familiar with the codebase. Any hints and thoughts would be appreciated!

**Comment by Johann150** [comment]
Hmm, I think that would be the place to implement it, but not sure if its the best way, will have too look more into the code base again. But for a proper review you should open a pull request!

**Comment by Johann150** [comment]
I think this issue was resolved with #331
