### ISSUE TITLE
codespan-reporting::Files not implemented for codespan::Files<String>

### ISSUE THREAD

**Issue by brightly-salty** [brendanzab/codespan#309]
When attempting to upgrade Gleam to 0.11.0 of codespan and codespan-reporting, I got the following error. 

```
error[E0277]: the trait bound `codespan::Files<std::string::String>: codespan_reporting::files::Files<'_>` is not satisfied
  --> src/diagnostic.rs:59:5
   |
59 |     emit(&mut buffer, &config, &files, &diagnostic).unwrap();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `codespan_reporting::files::Files<'_>` is not implemented for `codespan::Files<std::string::String>`
```

I guess I'm either missing something or this was overlooked.

**Comment by Johann150** [comment]
If I remember correctly, this was discussed a bit ago in the Matrix channel [on 2020-12-29](https://matrix.to/#/!oaTjvHZyVsPimZCAoK:matrix.org/$4pmwZTytO_850mFLa4DCLJRdj4EaP5AeSZpy3zRq2aA?via=matrix.org). I don't know why we did not fix this yet, I think the solution was quite simple. I'll make a PR. Maybe you could provide a minimal example that we could use in a test so this does not happen again in the future?

**Comment by brightly-salty** [comment]
Here's the function the error came from:
```rust
pub fn write_diagnostic(mut buffer: &mut Buffer, d: MultiLineDiagnostic, severity: Severity) {
    let mut files = Files::new();
    let file_id: FileId = files.add(d.file, d.src);

    let labels: Vec<Label<FileId>> = d
        .labels
        .iter()
        .map(|l| {
            Label::new(l.style, file_id, (l.location.start)..(l.location.end))
                .with_message(l.label.clone())
        })
        .collect();

    let diagnostic = codespan_reporting::diagnostic::Diagnostic::new(severity)
        .with_message(d.title)
        .with_labels(labels);

    let config = codespan_reporting::term::Config::default();
    emit(&mut buffer, &config, &files, &diagnostic).unwrap();
}
```
It isn't exactly minimal because it emits based on a custom Diagnostic struct.

**Comment by Johann150** [comment]
Thanks, I threw something together from this and other tests we have already.
