### ISSUE TITLE
Display is broken on some platforms

### ISSUE THREAD

**Issue by codec-abc** [brendanzab/codespan#311]
Hi,

Yesterday I was playing with [Gleam](https://github.com/gleam-lang) and noticed that the errors displayed in my terminal (Cmder on Windows 10) are kinda broken.

It looks like this :
![image](https://user-images.githubusercontent.com/1208646/105060112-4b401b80-5a78-11eb-8382-749367191bd9.png)

I guess it would be hard to have something that works on all platforms if it uses "advanced characters" (especially  on Windows). I think, it would be easier to run correctly on all platforms if diags could be displayed using only ASCII characters (ie whose range are in 0-127). I see many possible solution. One could be using an enum to instantiate a ``Char`` struct in Legacy (only ASCII) or Standard mode (make advantage of UTF-8 and Unicode) . Another one could be using cfg expression for the default value where it would change based on the platform it is compiled for. The one thing I don't know how to solve is by what should be replacing the characters that are troublesome. Especially for corners, they are single character for now and there isn't a look alike character in pure ASCII. More than one character could be used then but it would offset alignment. 

For the record, rustc seems to be only using ASCII chars.

**Comment by Johann150** [comment]
🤔 probably #105 should finally be wrapped up. That should solve this problem.

**Comment by codec-abc** [comment]
@lpil Just told me that Gleam compiler pipes it output to rebar3 (a "utility" for Erlang). If we don't do this it work as expected, so the problem is due to rebar3. Still, I think a compat mode would allow to avoid problem when piping stdout to a program that doesn't handle well non ascii chars.

**Comment by Johann150** [comment]
I think it would be nice if codespan implemented this by itself, but I think users of the library should already be able to do it by modifying the values in [`codespan_reporting::term::Chars`](https://docs.rs/codespan-reporting/0.11.0/codespan_reporting/term/struct.Chars.html).

**Comment by codec-abc** [comment]
Would you be OK if we provide 2 sets (one as of now, and one with pure ASCII) with the second that would be activated by a feature flag? So that way by only changing a line in the ``Cargo.toml`` people could change the character set used without effort. If this is OK for you I think I can do the PR.

**Comment by Johann150** [comment]
The feature flag sounds like a good idea. I am already on it!
