### ISSUE TITLE
Should non-`term` rendering backends live here?

### ISSUE THREAD

**Issue by azriel91** [brendanzab/codespan#313]
Heya, would this be the right repository for where a different kind of rendering backend (e.g. HTML output) would live?

For example, colour information provided through `<span style="..">` tags, spacing / line breaks needing `&nbsp;` and `<br />` to appear correctly on a web page.

It could live behind a feature flag.

If not, I guess one could make a separate crate and study https://github.com/brendanzab/codespan/blob/master/codespan-reporting/src/term/renderer.rs to output the same structure with different tags.

---

Worth noting, another way is to use the [ansi-to-html](https://crates.io/crates/ansi-to-html) crate that changes ANSI codes to HTML tags.

**Comment by Johann150** [comment]
Hi there, thanks for your Issue!

I think what you are talking about could also be implemented by using a custom implementation of [`termcolor::WriteColor`](https://docs.rs/termcolor/1.1.2/termcolor/trait.WriteColor.html) passed to `term::emit`. (also this might be related to #7)

On the more general question of other backends, I am not so sure. Maybe brendanzab can say something about that, if there even is a plan for that.
