### ISSUE TITLE
Cut codespan release with fix?

### ISSUE THREAD

**Issue by Jake-Shadle** [brendanzab/codespan#316]
I was upgrading to 0.11.0 and noticed that ca59f8afdaa05113816cdcb2c41b4a471cc1d50c fixed the issue where `codespan_reporting::files::Files` isn't implemented for codespan::Files, but it isn't released yet.

**Comment by Michael-F-Bryan** [comment]
I got bitten by this too. 

It [looks like](https://docs.rs/codespan/0.11.0/src/codespan/file.rs.html#224-225) the impl is guarded by a `#[cfg(feature = "reporting")]`, but the `Cargo.toml` doesn't actually say that feature exists.

```
error: failed to select a version for `codespan`.
    ... required by package `mdbook-linkcheck v0.7.3-alpha.0 (/home/michael/Documents/mdbook-linkcheck)`
versions that meet the requirements `=0.11.0` are: 0.11.0

the package `mdbook-linkcheck` depends on `codespan`, with features: `reporting` but `codespan` does not have these features.

failed to select a version for `codespan` which could resolve this conflict
```

**Comment by Johann150** [comment]
@Michael-F-Bryan the issue itself was already solved in #309, we only need one of the crate owners on crates.io (@Marwes or @brendanzab) to make a new release.

**Comment by brendanzab** [comment]
I'll get onto this today!

**Comment by brendanzab** [comment]
Should be released now!

**Comment by Jake-Shadle** [comment]
Thanks!
