### ISSUE TITLE
Use of moved value: `blue`

### ISSUE THREAD

**Issue by kvark** [brendanzab/codespan#322]
Seeing this error:
```
    Checking codespan-reporting v0.11.1
error[E0382]: use of moved value: `blue`
   --> /Users/dmalyshau/.cargo/registry/src/github.com-1ecc6299db9ec823/codespan-reporting-0.11.1/src/term/config.rs:180:55
    |
162 |     pub fn with_blue(blue: Color) -> Styles {
    |                      ---- move occurs because `blue` has type `Color`, which does not implement the `Copy` trait
...
178 |             secondary_label: ColorSpec::new().set_fg(Some(blue)).clone(),
    |                                                           ---- value moved here
179 | 
180 |             line_number: ColorSpec::new().set_fg(Some(blue)).clone(),
    |                                                       ^^^^ value used here after move
```
Rust: "rustc 1.50.0 (cb75ad5db 2021-02-10)"

**Comment by Johann150** [comment]
My guess is that you have a version of `termcolor` before `1.0.4`, because the Copy trait was first implemented on `Color` in 1.0.4. Could you please confirm this by showing the output of `cargo pkgid -p termcolor`? I'll update the Cargo.toml file to reflect the minimum version requirement if this is indeed the issue.

**Comment by kvark** [comment]
Yes, updating the termcolor does the trick.

**Comment by lopopolo** [comment]
Hi @Johann150 it looks like https://github.com/brendanzab/codespan/commit/e99c867339a877731437e7ee6a903a3d03b5439e was never released on crates.io. Would you be able to push a patch release?

**Comment by Johann150** [comment]
@lopopolo see #348
