### ISSUE TITLE
Implement `Ord` for `Severity`

### ISSUE THREAD

**Issue by bjchambers** [brendanzab/codespan#335]
This would allow determining the max severity as `diagnostics.iter().map(|d| d.severity).max()`. As is, there is no way (except manually matching) to determine whether there were diagnostics over a certain severity (eg., to fail if an error is reported but proceed if there are only warnings).

**Comment by Johann150** [comment]
I'm not sure this is even necessary, there is already a doc-test for this that passes:
https://github.com/brendanzab/codespan/blob/8d1762e6680731f9f920d7347af991c27670edd7/codespan-reporting/src/diagnostic.rs#L12-L19

https://github.com/brendanzab/codespan/runs/3300809770#step:4:247

**Comment by bjchambers** [comment]
I believe that `Severity::Bug > Severity::Error` works via the `PartialOrd`, where a return of `None` would correspond to `false`. But `max` requires `Ord` to indicate that all values are comparable.

**Comment by Johann150** [comment]
resolved with 5909730570873e41cac3a9961120c27524a55cba
