### ISSUE TITLE
Broken alignment in codespan-reporting with UTF-8 output

### ISSUE THREAD

**Issue by vivienm** [brendanzab/codespan#41]
I've been playing with a toy query language that includes UTF-8 string literals. On error reporting, visual alignment looks broken when using non-ASCII characters, even though spans are correct.

![shot_2018-11-23_161847](https://user-images.githubusercontent.com/2743798/48950494-9f542180-ef3b-11e8-9682-36acdeea0e31.png)

I guess this is due to paddings being computed using `str::len()`?

https://github.com/brendanzab/codespan/blob/a0311f3333a06c97bcb0993d95e1cb77fccc8917/codespan-reporting/src/emitter.rs#L106

**Comment by brendanzab** [comment]
Oh, thanks for reporting this! Will have to get onto a fix.

**Comment by brendanzab** [comment]
This also seems to interact with how we calculate `ColumnIndex`s too 🤔 - it's not just the emitter

**Comment by brendanzab** [comment]
You can see the issue here: https://github.com/brendanzab/codespan/pull/42#discussion_r237335852
