### ISSUE TITLE
[Request] Usage Guide

### ISSUE THREAD

**Issue by Phrohdoh** [brendanzab/codespan#48]
A usage guide / book for `codespan` would go a long way, I believe.

---

I am using `gluon` and `pikelet` as references but am having a difficult time figuring out how to correctly use this library (lifetime/ownership issues, some specifically regarding `FileMap`).

The two reference projects I mentioned make use of `lalrpop` which may make using `codespan` easier but I do not want to use `lalrpop` so I feel like I'm stuck out at sea here.

**Comment by emilk** [comment]
Strongly agree. I would like to give this library a try, but without any documentation or examples I don't feel it is worth exploring.

**Comment by lpil** [comment]
@emilk There is an example here https://github.com/brendanzab/codespan/blob/master/codespan-reporting/examples/emit.rs

**Comment by Phrohdoh** [comment]
FWIW I have dropped `codespan` in favor of [`mltt-span`](https://github.com/brendanzab/rust-nbe-for-mltt/tree/master/crates/mltt-span/src).

**Comment by brendanzab** [comment]
For more info see #52 - mltt-span is implementing traits implemented in language-reporting.

**Comment by brendanzab** [comment]
Thanks for the feedback on this! In #73 I simplified the interaction with the library greatly. I still feel we could make the examples more discoverable, so I'll leave #60 open for now.
