### ISSUE TITLE
Should we coordinate a migration to 'language-reporting'?

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#52]
@wycats, @nikomatsakis and @jonathandturner have done some great work in building on top of our work in codespan in [their branch here](https://github.com/nikomatsakis/language-reporting/tree/remove-codespan-dep) as part of their work on [Lark](https://github.com/lark-exploration/lark). It builds on top of the work of codespan, making it more configurable through the use of traits, and less confusing by using file ids. I've been using it in https://github.com/brendanzab/rust-nbe-for-mltt and have been quite happy!

The question though is: where to from here? Should we close down this repository and direct people to @wycats' project? Or should we try to take on the changes into this repository? I'm still a bit hesitant to take on the render-tree dependency, as I don't fully understand it yet.

Thoughts?

Useful PRs that might need to be up-streamed:

- #51: multiline error reporting
- #53: more space in emit output

**Comment by Marwes** [comment]
`render-tree` is the only thing I am a bit skeptical about. At some point I may want to seriously look at reducing the binary size of gluon and I may then need to look at replacing solutions that are too general (which I kind of feel `render-tree` might be). That's not to say it isn't a good idea to merge it though, it is a very specific problem to gluon and I may very well be able to workaround it anyway.

**Comment by brendanzab** [comment]
Yeah, that's my biggest scepticism, although I'm more concerned from a maintenance perspective. Curious to see if we can do some simplifications.

**Comment by brendanzab** [comment]
I think there would be some ergonomic improvements to implementing reporting using render-tree, but we'd have to weigh it up I think.

**Comment by brendanzab** [comment]
Other things that have been done is combining it into one crate. Are you happy with this @Marwes? It _does_ simplify things a little 🤔.

**Comment by Marwes** [comment]
> Other things that have been done is combining it into one crate. Are you happy with this @Marwes? It _does_ simplify things a little 🤔.

`codespan-lsp` is removed and I'd argue that at least that should be it's own crate given that it is only useful in the very specific usecase of writing a language server/client. Having `reporting` merged in isn't really an issue for me at least as I already always include it anyway. That might change but perhaps that is something that can be worked out later.

**Comment by brendanzab** [comment]
I'm feeling like I'm going to keep codespan alive for the time being because I don't have a clear idea of what is going on with language-reporting. It's been super valuable inspiration though! Most of the things I think we want from it are now in master or noted in issues, so I think I'll close this now.
