### ISSUE TITLE
Expand documentation

### ISSUE THREAD

**Issue by segeljakt** [brendanzab/codespan#60]
I want to use this crate in my project, but I don't know how to use it 🤔 

Given a file or string of source code, and a start and end location of a token, how do I produce an error message pointing to the location?

If someone helps explain, I can contribute with writing some documentation.

**Comment by brendanzab** [comment]
Yeah, it's a bit confusing! You first need a `CodeMap`, and then a `FileMap`, and then get indices from there. I've been thinking of ways to make the simple cases easier for some time now seeing as it keeps tripping people up. 😬 

Would definitely appreciate some help with the docs! You might also be interested in #52 which talks about some simplifications that we might be able to do as well. I'm also available to chat on https://gitter.im/codespan-rs/Lobby as well.

**Comment by segeljakt** [comment]
I think the example could be simplified to something like:

```
use codespan::{ByteIndex, ByteSpan, CodeMap};
use codespan_reporting::{
    emit,
    termcolor::{ColorChoice, StandardStream},
    Diagnostic, Label, Severity,
};

const SOURCE: &'static str = "fn main() { }";

fn main() {
    let mut code_map = CodeMap::new();
    code_map.add_filemap("test".into(), SOURCE.to_string());

    let error = Diagnostic::new(Severity::Error, "Unexpected type in `+` application")
        .with_label(
            Label::new_primary(ByteSpan::new(ByteIndex(3), ByteIndex(6)))
                .with_message("Expected integer but got string"),
        )
        .with_code("E0001");

    let writer = StandardStream::stderr(ColorChoice::Auto);
    emit(&mut writer.lock(), &code_map, &error).unwrap();
    println!();
}
```

**Comment by brendanzab** [comment]
Codespan is a lot less tricky to understand now that we don't use global byte indices. If you have any other problems feel free to make some more issues!

**Comment by segeljakt** [comment]
Awesome thanks 😊
