### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#78]
Lots of work has been done to improve the API in the time since the last release. What do we need to do to get v0.4.0 out the door?

cc. @Marwes

**Comment by est31** [comment]
Friendly bump

**Comment by brendanzab** [comment]
Thanks! Are you waiting on some of the new features/improvements?

**Comment by brendanzab** [comment]
I've been holding off because I don't yet have a trait abstraction for the files and spans... which could make it harder for somebody to migrate if they wanted to. But maybe I just need to get on with it. 😬

**Comment by est31** [comment]
@brendanzab yes, I'd love to have good tabs support. Trait support seems like an okay reason to wait with a release. For now I guess I'll be using master.

**Comment by brendanzab** [comment]
Cool! Sadly I have a bit on my plate with the work project that uses codespan right now - it might be a month or so until I'll be able to get back to codespan itself. Feel free to keep bugging me about it though!

**Comment by brendanzab** [comment]
Thinking I'm just going to release this now! It's been long enough!

**Comment by brendanzab** [comment]
If we have users struggling to migrate we can look at releasing features to help later down the line.
