### ISSUE TITLE
Custom databases (Salsa support)

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#79]
It would be nice to be able to define custom `Files`-style databases depending on the needs of a project. 

- People might want to use something like [Salsa](https://github.com/salsa-rs/salsa/) to manage their source files.
- When starting off building a language, a 'SingleFile' database (that only took a single file) might be a better solution than #56.
- Others might want to use a more compact span representation than the one used currently. For example compressing it, as is done in rustc.

The [language-reporting](https://github.com/wycats/language-reporting) fork defines [`ReportingSpan` and `ReportingFiles`](https://github.com/wycats/language-reporting/blob/b021c87e0d4916b5f32756151bf215c220eee52d/src/span.rs#L18-L42) traits which might be useful for inspiration.

**Comment by brendanzab** [comment]
Inching towards a `Files` trait here: https://github.com/brendanzab/codespan/compare/traits

Still does not compile though - working through how to pull everything out nicely. The crate structure is a tad awkward though - now codespan is only depended on in order to implement `Span` and `Files`.

**Comment by brendanzab** [comment]
I think it'd probably also be nice to implement the LSP support in terms of these traits too.

**Comment by brendanzab** [comment]
It would also be interesting if we could have a subtrait that also provided URLs for `codespan-lsp`, which would mean we wouldn't have to supply the `correlate_file_url` closure.

**Comment by Marwes** [comment]
Getting some sort of trait in would be nice before upgrading for me as the lack of being able to take individual `Arc<FileMap>` out makes it impossible to work with `Files` concurrently (reading from one file while adding others).

I can take https://github.com/brendanzab/codespan/compare/traits and get it working but I don't really know if we must/should make any additional changes to the traits.
