### ISSUE TITLE
Support for the Language Server Protocol

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#8]
It would be nice to have a clean way of building language servers using codespan. I'm not sure how much of it we will be able to automate though, and how much would be up to the user to build. At least having some nice serializers for the diagnostics would be handy.

**Comment by Marwes** [comment]
LSP Diagnostic https://github.com/gluon-lang/languageserver-types/blob/2a1adc0ea441792c614d3401aec21a99acc4dddd/src/lib.rs#L117-L144

Location translation https://github.com/gluon-lang/gluon_language-server/blob/dbcaf93cb4e1d7f5043047523dacf8674410715d/src/location_translation.rs (LSP uses UTF-16 codeunits as "characters" for some ungodly reason)

**Comment by Marwes** [comment]
Working on updating gluon's language server so will tackle this and #9 during that.

**Comment by Phrohdoh** [comment]
What is the status of converting between LSP types and codespan types?

**Comment by Marwes** [comment]
@Phrohdoh It is possible to translate between locations and diagnostics atm https://docs.rs/codespan-lsp/0.1.0/codespan_lsp/

**Comment by brendanzab** [comment]
Some good thoughts from @wycats on the Gitter channel:

> My biggest frustration with LSPs is that it seems like there's this huge blob of vscode stuff you need to do to get started that is poorly documented. The thing I wish codespan-lsp did was just give me a small Rust API for handling the events and hook everything up for me.
>
> It's like: ok, the protocol is agnostic to socket vs http vs whatever. Ok sure. But what does vscode actually DO to negotiate with the process it opens? 🤷‍♂️ When I look at gluon and rust-rls, I see that they have copious amounts of connection code in common.

**Comment by brendanzab** [comment]
Things could always be improved, but I think I'll treat this as done for now.
