### ISSUE TITLE
Allow for files to be incrementally updated

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/codespan#83]
The LSP defines some incremental update types for working with text documents:

- [`TextEdit`](https://microsoft.github.io/language-server-protocol/specification#textedit)
- [`TextEdit[]`](https://microsoft.github.io/language-server-protocol/specification#textedit-1)
- [`TextDocumentEdit`](https://microsoft.github.io/language-server-protocol/specification#textdocumentedit)

These are used in the [`WorkspaceEdit`](https://microsoft.github.io/language-server-protocol/specification#workspaceedit) type. It would be nice to provide analogues to these operations in our `Files` type.

**Comment by matklad** [comment]
One additional concern here is how to translate between BytePos -> LineCol coordinates in the presence of edits. In rust-analyzer, we hit this in the following case:

* our internal coordiantes are byte offsets
* the result of the refactoring is a set of edits (in byte-offset coordinates) and a final position of a curosr (byte offset in a file **with changes**)
* on the LSP layer, we need to translate this to (line, col) coordinates. Doing this for cursor offset is tricky.

This PR implements that logic: https://github.com/rust-analyzer/rust-analyzer/pull/325

Additional random tidbit:

I was surprised that IntelliJ uses sorted array of offsets and not some fancy tree data structure, a-la xi-rope's monoid tree, to translate offsets: https://github.com/JetBrains/intellij-community/blob/513e5d6cdaa66c93e130393045bcc038537454d3/platform/core-impl/src/com/intellij/openapi/editor/impl/LineSet.java

In particular, they just update the array on changes: https://github.com/JetBrains/intellij-community/blob/513e5d6cdaa66c93e130393045bcc038537454d3/platform/core-impl/src/com/intellij/openapi/editor/impl/LineSet.java#L70-L94

IIUC, for things like grapheme clusters IntelliJ doesn't use indices at all, and instead does a linear scan withing a single line.

**Comment by brendanzab** [comment]
Thanks for the added information, that's really helpful!

**Comment by brendanzab** [comment]
Gonna close this because now user's can implement their own file databases using the `Files` trait.
