### ISSUE TITLE
Allow removal and updating of the FileMap's inside CodeMap's

### ISSUE THREAD

**Issue by Marwes** [brendanzab/codespan#9]
For language servers the sources will be frequently modified and old sources (`FileMap`s) will be thrown out eventually. As `CodeMap` works now though, it is not possible to remove a source once it is added which means that memory use will grow for each modification to a file.

If removal of `FileMap`s are possible we could maybe run into fragmentation issues for `Span` allocation but I think that in practice this can largely be ignored (or we could use some simple memory allocator approach to remedy memory fragmentation).

**Comment by Phrohdoh** [comment]
Has there been any progress on this?

**Comment by Marwes** [comment]
You can use https://docs.rs/codespan/0.2.0/codespan/struct.CodeMap.html#method.update for a naive approach (it uses first-fit to find a gap in the spans to fit the new source into)

**Comment by brendanzab** [comment]
Ah, I just realised that I made a dupe of this here: #83.

Which of these do you think is better for the current state of codespan @Marwes?

**Comment by Marwes** [comment]
I guess we can close this since there is an implementation now, even if it is naive.
